### ISSUE TITLE
Access to PCB's

### ISSUE THREAD

**Issue by davy932** [mjuhanne/fyrtur-esp#6]
Hi,

I have 5 of the assembled PCB's spare, based in the UK.  If you have anyone contact you happy to sell on at cost price.

**Comment by JB-BYS** [comment]
If mine don't work i will send you a message back, thanks !
btw, what is the price ? :)

**Comment by JB-BYS** [comment]
@davy932 i will bought it ;)

**Comment by davy932** [comment]
I have 5 boards and 5 ESP8266 chips to solder on. Do you want them all? The boards, populated and shipped where only $9.84 (USD) / £8If you want the ESPs also Happy to sell, £13£21 total plus postage RegardsDavid Evans+353 87 2938629On 25 Jan 2023, at 19:43, Jules Brugot ***@***.***> wrote:﻿
@davy932 i will bought it ;)

**Comment by JB-BYS** [comment]
okay !
how do we proceed for the shipping ?

**Comment by davy932** [comment]
What is your shipping address - I can calculate the value. You can pay via PayPal? If you wish WhatsApp on the number belowRegardsDavid Evans+353 87 2938629On 26 Jan 2023, at 17:18, Jules Brugot ***@***.***> wrote:﻿
okay !
how do we proceed for the shipping ?

**Comment by tracetechnical** [comment]
Do you still have any of these spare? @davy932

**Comment by davy932** [comment]
Sorry.SoldOn 4 Nov 2023, at 20:58, Alex Bush ***@***.***> wrote:﻿
Do you still have any of these spare?

**Comment by tracetechnical** [comment]
No worries, I cant close this issue, but you may want to now theyre all gone

**Comment by JB-BYS** [comment]
I Have actually 4 of them in stock if someone is searching them
